name: Stats
on:
  schedule:
   # https://crontab.guru/once-a-day
   - cron: 0 0 * * *
  workflow_dispatch: {}

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/app-stats-action@v1.0.4
        id: stats
        with:
          id: 74129
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - run: "echo installations: '${{ steps.stats.outputs.installations }}'"
      - run: "echo most popular repositories: '${{ steps.stats.outputs.popular_repositories }}'"
