name: Test
on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10, 12]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install pnpm and project dependencies
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.4.12
          run_install: true
      - name: Check lint
        run: pnpm run check-lint
      - name: Run tests with coverage
        run: pnpm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
